// STATES ACTIONS
export const LOADING_DATA = "LOADING_DATA"

// ERRORS ACTIONS
export const GET_ERRORS = "GET_ERRORS"

// USER ACTIONS
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"
